name: cheshire
channels:
  - conda-forge
dependencies:
  # Packages required for setting up the environment
  - pip>=21,<25

  # Jupyter packages:
  - jupyterlab>=3.2,<5
  - nbconvert>=6,<8 # Used to clear notebook outputs in pre-commit hooks

  # Use pip to install the package defined by this repo for development:
  - pip:
      - --editable ./[dev,doc,tests]
